Document: piclone
Title: Debian piclone Manual
Author: <insert document author here>
Abstract: This manual describes what piclone is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/piclone/piclone.sgml.gz

Format: postscript
Files: /usr/share/doc/piclone/piclone.ps.gz

Format: text
Files: /usr/share/doc/piclone/piclone.text.gz

Format: HTML
Index: /usr/share/doc/piclone/html/index.html
Files: /usr/share/doc/piclone/html/*.html
